# Generated by Django 2.2.7 on 2020-08-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200827_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='no_of_click',
        ),
    ]
