# Generated by Django 2.2.7 on 2020-09-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_remove_record_no_of_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
