# Generated by Django 2.2.7 on 2020-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200901_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='unique_id',
            field=models.CharField(max_length=20),
        ),
    ]
