# Generated by Django 2.2.7 on 2020-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20200901_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
