# Generated by Django 2.2.7 on 2020-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20200901_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='description',
            field=models.TextField(blank=True, default='None Given', null=True),
        ),
    ]
