# Generated by Django 2.2.7 on 2020-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20200901_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='description',
            field=models.TextField(blank=True, default='None Given', help_text='Give a brief description about the site', null=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='url',
            field=models.URLField(help_text='e.g. http(s)://www.<name_of_website>.com'),
        ),
    ]
