# Generated by Django 2.2.7 on 2020-09-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20200901_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='name',
            field=models.CharField(help_text='URL name e.g Tinny', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='unique_id',
            field=models.CharField(help_text='Type in a I.D or one will be automatically assigned to your URL', max_length=20, unique=True),
        ),
    ]
