# Generated by Django 2.2.7 on 2020-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_auto_20200901_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='name',
            field=models.CharField(default='No name', help_text='URL name e.g Tinny', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Type in a I.D or one will be automatically assigned to your URL', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='url',
            field=models.URLField(help_text='e.g. http(s)://www.name_of_website.com'),
        ),
    ]
